# Dimensiones

Las dimensiones de los elementos escalar, vector, matriz, y tensor, nos dicen la dirección o direcciones a las que nos podemos mover en esos elementos.

Los arrays de `numpy` tienen una propiedad llamada `ndim` que nos dice cual es la dimensión de un elemento array, por otro lado, también esta la propiedad `shape` que nos dice la forma que tiene un array.

In [1]:
import numpy as np

Creamos los elementos:

In [25]:
escalar = 5.26
vector = np.array([1,2,3])
matriz = np.array([[1,2], [3,4], [5,6]])
tensor = np.array([
  [[1,2], [3,4], [5,6]],
  [[7,8], [9,10], [11,12]],
  [[13,14], [15,16], [17,18]],
  [[19,20], [21,22], [23,24]],
])

## Dimensión de un `escalar`

In [18]:
escalar.ndim

AttributeError: 'float' object has no attribute 'ndim'

In [17]:
escalar.shape

AttributeError: 'float' object has no attribute 'shape'

Un escalar al ser un valor por si solo, no cuenta con dimensiones.




<div class="alert alert-warning" >
    <p>
        <b style="font-size: 1.5em;">⚠️</b> 
        Un punto importante a resaltar es que la variable escalar al no ser un array de <b>numpy</b> no es posible acceder a las propiedades <code>ndim</code> y <code>shpe</code>.
    </p>
</div>

## Dimensión de un `vector`

In [21]:
print(f"Dimensión: {vector.ndim}")
print(f"Forma: {vector.shape}")
print(vector)

Dimensión: 1
Forma: (3,)
[1 2 3]


`ndim` nos dice que el vector es de una dimensión.

La tupla que nos regresa la propiedad `shape` nos da en su primer posición el número de elementos que tiene el vector, o bien las posiciones en el mismo.

## Dimensión de una `matriz`

In [26]:
print(f"Dimensión: {matriz.ndim}")
print(f"Forma: {matriz.shape}")
print(matriz)


Dimensión: 2
Forma: (3, 2)
[[1 2]
 [3 4]
 [5 6]]


`ndim` nos dice que la matriz es de dos dimensiones.

Mientras que `shape` nos da la forma de la matriz, la cual podemos interpretar de la siguiente manera:
- `(numero_filas, numero_columnas)`: La matriz cuenta con 3 filas y 2 columnas.

## Dimensión de un `tensor`

In [27]:
print(f"Dimensión: {tensor.ndim}")
print(f"Forma: {tensor.shape}")
print(tensor)

Dimensión: 3
Forma: (4, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


`ndim` nos dice que el tensor cuenta con 3 dimensiones.

`shape` nos da la forma del tensor con una tupla de 3 elementos, su interpretación:
- `(numero_matrices, numero_fila, numero_columnas)`: El tensor esta conformado por 3 matries con 3 filas y 2 columnas (cada matriz).

<div class="alert alert-info" >
    <p>
        <b style="font-size: 1.5em;">💡</b> 
        Tanto las matrices como los tensores son un "vector de vectores", cada dimensión es el nivel de anidamiento en los vectores.
    </p>
</div>