# Transposición, suma de matrices y escalares

- **Transponer de una matriz**: Cambiar las filas por columnas y las columnas por filas, manteniendo los elementos de la diagonal en el mismo lugar.
- **Transponer un vector**: Al transponer un vector fila obtenemos un vector columna.

Liberías

In [1]:
import numpy as np

## Transosición

### Transpuesda de un vector

In [2]:
vector = np.array([1,2,3,4])
print(f"Vector: {vector} ")
print(f"Transpuesto: {vector.T}")

Vector: [1 2 3 4] 
Transpuesto: [1 2 3 4]


Con la herramienta (python) no podemos ver como el vector se transpudo a un vectro columna, pero se vería así:

$$
{\begin{bmatrix}
   a_{11} & a_{12} 
\end{bmatrix}}^t

=
 
\begin{bmatrix}
   a_{11}  \\
   a_{21} 
\end{bmatrix}
 

$$

### Transpuesta de una matriz

In [3]:
matriz = np.array([[1,2], [3,4], [5,6]])
matriz_t = matriz.T

print(f"Matriz: \n {matriz} \n shape: {matriz.shape} \n")
print(f"Transpuesta: \n {matriz_t} \n shape: {matriz_t.shape}")

Matriz: 
 [[1 2]
 [3 4]
 [5 6]] 
 shape: (3, 2) 

Transpuesta: 
 [[1 3 5]
 [2 4 6]] 
 shape: (2, 3)


### Transpuesta de un tensor

In [4]:
tensor = np.array([
  [[1,2], [3,4], [5,6]],
  [[7,8], [9,10], [11,12]],
  [[13,14], [15,16], [17,18]],
  [[19,20], [21,22], [23,24]],
])

print(f"Tensor: \n {tensor}")
print(f"shape: {tensor.shape}")

Tensor: 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
shape: (4, 3, 2)


In [5]:
tensor_T = tensor.T
print(f"Transpuesta: \n {tensor_T}")
print(f"shape: {tensor_T.shape}")

Transpuesta: 
 [[[ 1  7 13 19]
  [ 3  9 15 21]
  [ 5 11 17 23]]

 [[ 2  8 14 20]
  [ 4 10 16 22]
  [ 6 12 18 24]]]
shape: (2, 3, 4)


## Suma de matrices

La suma entre matrices puede realizarse siempre y cuando éstas tengan la misma forma (mismo numero de filas y columnas)

In [6]:
suma = matriz + matriz_t

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

Al sumnar la matriz transpuesta con la matriz original obtenemos un error, pues la transpuesta invirtio el número de filas y columnas.

In [7]:
matriz_cuadrada = np.array([[1,2], [3,4]])
matriz_cuadrada_t = matriz_cuadrada.T

print(f"Matriz: \n {matriz_cuadrada} \n shape: {matriz_cuadrada.shape}")
print(f"Transpuesta: \n {matriz_cuadrada_t} \n shape: {matriz_cuadrada_t.shape}")

Matriz: 
 [[1 2]
 [3 4]] 
 shape: (2, 2)
Transpuesta: 
 [[1 3]
 [2 4]] 
 shape: (2, 2)


In [8]:
suma = matriz_cuadrada + matriz_cuadrada_t
suma

array([[2, 5],
       [5, 8]])

Al sumar dos matrices, lo que hacemos es sumar cada elemento con su respectiva posición
$$
\begin{bmatrix}
   a_{11} & a_{12} \\
   a_{21} & a_{22}
\end{bmatrix}
 
 + 

 \begin{bmatrix}
   b_{11} & b_{12} \\
   b_{21} & b_{22}
\end{bmatrix}

=

 \begin{bmatrix}
   a_{11}+b_{11} & a_{12}+b_{12} \\
   a_{21}+b_{21} & a_{22}+b_{22}
\end{bmatrix}
$$

<p align="center"> El ejemplo anterior seria: </p>

$$
\begin{bmatrix}
   1 & 2 \\
   3 & 4
\end{bmatrix}
 
 + 

 \begin{bmatrix}
   1 & 3 \\
   2 & 4
\end{bmatrix}

=

 \begin{bmatrix}
   1+1 & 2+3 \\
   3+2 & 4+4
\end{bmatrix}
$$

📌 Una matriz es cuadrada cuando tiene el mismo número de filas y columnas.

### Suma de una matriz y un escalar

In [9]:
escalar = np.array(5.55)
matriz = np.array([[1,2,3,4], [5,6,7,8]])

suma_m_e = matriz + escalar
print(suma_m_e)

[[ 6.55  7.55  8.55  9.55]
 [10.55 11.55 12.55 13.55]]


El valor escalar se suma a cada elemento de la matriz.

$$
\begin{bmatrix}
   a_{11} & a_{12} \\
   a_{21} & a_{22}
\end{bmatrix}
 
 + 

 b

=

 \begin{bmatrix}
   a_{11}+b & a_{12}+b \\
   a_{21}+b & a_{22}+b
\end{bmatrix}
$$