# Producto interno

El producto interno permite calcular magnitudes, distancias y ángulos en un espacio vectorial.

Es una forma determinada de unir dos vectores para obtener un número. Lo podemos representar de la siguiente manera:

$$
\begin{bmatrix}
   a_{11}  \\
   a_{21} 
\end{bmatrix}

\centerdot

\begin{bmatrix}
   b_{11}  \\
   b_{21} 
\end{bmatrix}

=
a_{11} * b_{11} + a_{21}*b_{21}
$$

Ejemplo:

$$
\begin{bmatrix}
   2  \\
   7  \\
   1
\end{bmatrix}

\centerdot

\begin{bmatrix}
   8  \\
   2  \\
   8
\end{bmatrix}

=
(2 * 8) + (7 *2 ) + (1*8) = 16+14+8 = 38
$$

In [1]:
import numpy as np

In [2]:
v1 = np.array([2,7,1])
v2 = np.array([8,2,8])
np.dot(v1, v2)

38

## Producto interno entre una matriz y un vector

Cuando calculamos el producto interno entre dos vectores obtenemos un valor escalar (elemento que en su conjunto forma un vector).

Cuando calculamos el producto interno una matriz y un vector, obtemos un vector como resultado (un vector en conjunto con otros forma una matriz).

Sin embargo para calcular el producto interno de estos dos elementos, la matriz debe tener el mismo número de columnas que un vector tiene de elementos.


Lo podemos representar:

$$
\begin{bmatrix}
   a_{11} & a_{12} \\ 
   a_{21} & a_{22} \\ 
   a_{31} & a_{32} \\ 
\end{bmatrix}

\centerdot
 
\begin{bmatrix}
   b_{11}  \\ 
   b_{21}
\end{bmatrix}

=
 
\begin{bmatrix}
   a_{11}*b_{11} + a_{12}*b_{21} \\ 
   a_{21}*b_{11} + a_{22}*b_{21} \\
   a_{21}*b_{11} + a_{22}*b_{21} 
\end{bmatrix}
$$

Ejemplo:
$$
\begin{bmatrix}
   1 & 2 \\ 
   3 & 4 \\ 
   5 & 6 \\ 
\end{bmatrix}

\centerdot
 
\begin{bmatrix}
   2  \\ 
   3
\end{bmatrix}

=
 
\begin{bmatrix}
   (1*2) + (2*3) \\
   (3*2) + (4*3) \\
   (5*2) + (6*3)
\end{bmatrix}

=
 
\begin{bmatrix}
   2 + 6 \\
   6 + 12 \\
   10 + 18
\end{bmatrix}

=
 
\begin{bmatrix}
   8\\
   20\\
   28
\end{bmatrix}
$$




In [3]:
vector = np.array([2,3])
matriz = np.array([[1,2], [3,4],[5,6]])

In [4]:
print(matriz.dot(vector))
print(np.dot(matriz, vector))

[ 8 18 28]
[ 8 18 28]


No es lo mismo una multiplicación de un vector con otro vector y con otra matriz, pues como resultado obtenemos la multiplicaciones de los valores que conforman estos elementos en la estructura de mayor dimensión.

Si multiplicamos dos vectores, obtenemos un vector.
$$
\begin{bmatrix}
   a_{11}  \\
   a_{21} 
\end{bmatrix}

\centerdot

\begin{bmatrix}
   b_{11}  \\
   b_{21} 
\end{bmatrix}

=
\begin{bmatrix}
   a_{11} * b_{11}  \\
   a_{21} * b_{21} 
\end{bmatrix}
$$


Si multiplicamos una matriz con un vector, obtenemos una matriz.

$$
\begin{bmatrix}
   a_{11} & a_{12} \\ 
   a_{21} & a_{22} \\ 
   a_{31} & a_{32} \\ 
\end{bmatrix}

\centerdot
 
\begin{bmatrix}
   b_{11}  \\ 
   b_{21}
\end{bmatrix}

=
 
\begin{bmatrix}
   a_{11}*b_{11} & a_{12}*b_{21} \\ 
   a_{21}*b_{11} & a_{22}*b_{21} \\
   a_{21}*b_{11} & a_{22}*b_{21} 
\end{bmatrix}
$$


Ejemplo de vector * vector:

$$
\begin{bmatrix}
   2  \\
   7  \\
   1
\end{bmatrix}

\centerdot

\begin{bmatrix}
   8  \\
   2  \\
   8
\end{bmatrix}

=
\begin{bmatrix}
   2 * 8 \\
   7 *2  \\
   1*8
\end{bmatrix}
=
\begin{bmatrix}
   16 \\
   14 \\
   8
\end{bmatrix}

$$

Ejemplo de matriz * vector:
$$
\begin{bmatrix}
   1 & 2 \\ 
   3 & 4 \\ 
   5 & 6 \\ 
\end{bmatrix}

\centerdot
 
\begin{bmatrix}
   2  \\ 
   3
\end{bmatrix}

=
 
\begin{bmatrix}
   (1*2) & (2*3) \\
   (3*2) & (4*3) \\
   (5*2) & (6*3)
\end{bmatrix}

=
 
\begin{bmatrix}
   2 & 6 \\
   6 & 12 \\
   10 & 18
\end{bmatrix}

$$

In [5]:
print("Multiplicación de dos vectores: ")
print(f"Vector 1: {v1}")
print(f"Vector 2: {v2}")
print(f"v1 * v2: {v1*v2}")

Multiplicación de dos vectores: 
Vector 1: [2 7 1]
Vector 2: [8 2 8]
v1 * v2: [16 14  8]


In [6]:
print("Multiplicación de una matriz y un vector: ")
print(f"Matriz: \n {matriz}\n")
print(f"Vector: {vector}")
print(f"matriz * vector: \n {matriz*vector}")

Multiplicación de una matriz y un vector: 
Matriz: 
 [[1 2]
 [3 4]
 [5 6]]

Vector: [2 3]
matriz * vector: 
 [[ 2  6]
 [ 6 12]
 [10 18]]


## Producto interno entre dos matrices

Para que dos matrices puedan ser tener un producto interno el número de columnas de la primer matriz debe ser igual al número de filas de la segunda.

$$
\begin{bmatrix}
   a_{11} & a_{12} \\ 
   a_{21} & a_{22} \\ 
   a_{31} & a_{32} \\ 
\end{bmatrix}

\centerdot
 
\begin{bmatrix}
   b_{11} & b_{12} \\ 
   b_{21} & b_{22}
\end{bmatrix}

=
 
\begin{bmatrix}
   (a_{11}*b_{11}) + (a_{12} *  b_{21})   &  (a_{11}*b_{12}) + (a_{12} *  b_{22}) \\
   (a_{21}*b_{11}) + (a_{22} *  b_{21})   &  (a_{21}*b_{12}) + (a_{22} *  b_{22}) \\
   (a_{31}*b_{11}) + (a_{32} *  b_{21})   &  (a_{31}*b_{12}) + (a_{32} *  b_{22}) 
\end{bmatrix}
$$


Ejemplo:
$$
\begin{bmatrix}
   1 & 2 & 3 \\ 
   4 & 5 & 6 \\ 
   7 & 8 & 9 \\ 
   10 & 11 & 12 
\end{bmatrix}

\centerdot
 
\begin{bmatrix}
   2 & 3 \\ 
   5 & 7 \\
   11 & 13
\end{bmatrix}

=
 
\begin{bmatrix}
   (1*2) + (2*5) + (3*11) & (1*3) + (2*7) + (3*13) \\
   
   (4*2) + (5*5) + (6*11) & (4*3) + (5*7) + (6*13) \\
   (7*2) + (8*5) + (9*11) & (7*3) + (8*7) + (9*13) \\
   (10*2) + (11*5) + (12*11) & (10*3) + (11*7) + (12*13) \\
\end{bmatrix}

=
 
\begin{bmatrix}
   2 + 10 + 33 & 3 + 14 + 39 \\   
   8 + 25 + 66 & 12 + 35 + 78 \\
   14 + 40 + 99 & 21 + 56 + 117\\
   20 + 55 + 132 & 30 + 77 + 156
\end{bmatrix}

=
 
\begin{bmatrix}
   45 & 56 \\   
   99 & 125 \\
   153 & 194 \\
   207 & 263
\end{bmatrix}
$$

In [7]:
matriz_A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) 
matriz_B = np.array([[2,3], [5,7], [11,13]])

print(f"Matriz A: \n {matriz_A}")
print(f"Matriz B: \n {matriz_B}")
print("Producto interno de A y B:")
np.dot(matriz_A, matriz_B)

Matriz A: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Matriz B: 
 [[ 2  3]
 [ 5  7]
 [11 13]]
Producto interno de A y B:


array([[ 45,  56],
       [ 99, 125],
       [153, 194],
       [207, 263]])

📌**NOTA**: No es lo mismo calcular el producto de las patrices `A` y `B`, que de `B` * `A`.

In [8]:
np.dot(matriz_B, matriz_A)

ValueError: shapes (3,2) and (4,3) not aligned: 2 (dim 1) != 4 (dim 0)

Al intentar hacer el producto interno cambiando el orden de las matrices obtenemos un error de dimensionalida, pues las columnas de la matriz `B` no coinciden con el número filas de la matriz `A`

In [10]:
print(f"Matriz B: filas = {matriz_B.shape[0]}, columnas = {matriz_B.shape[1]}")
print(f"Matriz A: filas = {matriz_A.shape[0]}, columnas = {matriz_A.shape[1]}")

Matriz B: filas = 3, columnas = 2
Matriz A: filas = 4, columnas = 3
