# Producto interno

El producto interno permite calcular magnitudes, distancias y ángulos en un espacio vectorial.

Es una forma determinada de unir dos vectores para obtener un número. Lo podemos representar de la siguiente manera:

$$
\begin{bmatrix}
   a_{11}  \\
   a_{21} 
\end{bmatrix}

\centerdot

\begin{bmatrix}
   b_{11}  \\
   b_{21} 
\end{bmatrix}

=
a_{11} * b_{11} + a_{21}*b_{21}
$$

Ejemplo:

$$
\begin{bmatrix}
   2  \\
   7  \\
   1
\end{bmatrix}

\centerdot

\begin{bmatrix}
   8  \\
   2  \\
   8
\end{bmatrix}

=
(2 * 8) + (7 *2 ) + (1*8) = 16+14+8 = 38
$$

In [1]:
import numpy as np

In [2]:
v1 = np.array([2,7,1])
v2 = np.array([8,2,8])
np.dot(v1, v2)

38

## Producto interno entre una matriz y un vector

Cuando calculamos el producto interno entre dos vectores obtenemos un valor escalar (elemento que en su conjunto forma un vector).

Cuando calculamos el producto interno una matriz y un vector, obtemos un vector como resultado (un vector en conjunto con otros forma una matriz).

Sin embargo para calcular el producto interno de estos dos elementos, la matriz debe tener el mismo número de columnas que un vector tiene de elementos.


Lo podemos representar:

$$
\begin{bmatrix}
   a_{11} & a_{12} \\ 
   a_{21} & a_{22} \\ 
   a_{31} & a_{32} \\ 
\end{bmatrix}

\centerdot
 
\begin{bmatrix}
   b_{11}  \\ 
   b_{21}
\end{bmatrix}

=
 
\begin{bmatrix}
   a_{11}*b_{11} + a_{12}*b_{21} \\ 
   a_{21}*b_{11} + a_{22}*b_{21} \\
   a_{21}*b_{11} + a_{22}*b_{21} 
\end{bmatrix}
$$

Ejemplo:
$$
\begin{bmatrix}
   1 & 2 \\ 
   3 & 4 \\ 
   5 & 6 \\ 
\end{bmatrix}

\centerdot
 
\begin{bmatrix}
   2  \\ 
   3
\end{bmatrix}

=
 
\begin{bmatrix}
   (1*2) + (2*3) \\
   (3*2) + (4*3) \\
   (5*2) + (6*3)
\end{bmatrix}

=
 
\begin{bmatrix}
   2 + 6 \\
   6 + 12 \\
   10 + 18
\end{bmatrix}

=
 
\begin{bmatrix}
   8\\
   20\\
   28
\end{bmatrix}
$$




In [3]:
vector = np.array([2,3])
matriz = np.array([[1,2], [3,4],[5,6]])

In [4]:
print(matriz.dot(vector))
print(np.dot(matriz, vector))

[ 8 18 28]
[ 8 18 28]


No es lo mismo una multiplicación de un vector con otro vector y con otra matriz, pues como resultado obtenemos la multiplicaciones de los valores que conforman estos elementos en la estructura de mayor dimensión.

Si multiplicamos dos vectores, obtenemos un vector.
$$
\begin{bmatrix}
   a_{11}  \\
   a_{21} 
\end{bmatrix}

\centerdot

\begin{bmatrix}
   b_{11}  \\
   b_{21} 
\end{bmatrix}

=
\begin{bmatrix}
   a_{11} * b_{11}  \\
   a_{21} * b_{21} 
\end{bmatrix}
$$


Si multiplicamos una matriz con un vector, obtenemos una matriz.

$$
\begin{bmatrix}
   a_{11} & a_{12} \\ 
   a_{21} & a_{22} \\ 
   a_{31} & a_{32} \\ 
\end{bmatrix}

\centerdot
 
\begin{bmatrix}
   b_{11}  \\ 
   b_{21}
\end{bmatrix}

=
 
\begin{bmatrix}
   a_{11}*b_{11} & a_{12}*b_{21} \\ 
   a_{21}*b_{11} & a_{22}*b_{21} \\
   a_{21}*b_{11} & a_{22}*b_{21} 
\end{bmatrix}
$$


Ejemplo de vector * vector:

$$
\begin{bmatrix}
   2  \\
   7  \\
   1
\end{bmatrix}

\centerdot

\begin{bmatrix}
   8  \\
   2  \\
   8
\end{bmatrix}

=
\begin{bmatrix}
   2 * 8 \\
   7 *2  \\
   1*8
\end{bmatrix}
=
\begin{bmatrix}
   16 \\
   14 \\
   8
\end{bmatrix}

$$

Ejemplo de matriz * vector:
$$
\begin{bmatrix}
   1 & 2 \\ 
   3 & 4 \\ 
   5 & 6 \\ 
\end{bmatrix}

\centerdot
 
\begin{bmatrix}
   2  \\ 
   3
\end{bmatrix}

=
 
\begin{bmatrix}
   (1*2) & (2*3) \\
   (3*2) & (4*3) \\
   (5*2) & (6*3)
\end{bmatrix}

=
 
\begin{bmatrix}
   2 & 6 \\
   6 & 12 \\
   10 & 18
\end{bmatrix}

$$

In [5]:
print("Multiplicación de dos vectores: ")
print(f"Vector 1: {v1}")
print(f"Vector 2: {v2}")
print(f"v1 * v2: {v1*v2}")

Multiplicación de dos vectores: 
Vector 1: [2 7 1]
Vector 2: [8 2 8]
v1 * v2: [16 14  8]


In [6]:
print("Multiplicación de una matriz y un vector: ")
print(f"Matriz: \n {matriz}\n")
print(f"Vector: {vector}")
print(f"matriz * vector: \n {matriz*vector}")

Multiplicación de una matriz y un vector: 
Matriz: 
 [[1 2]
 [3 4]
 [5 6]]

Vector: [2 3]
matriz * vector: 
 [[ 2  6]
 [ 6 12]
 [10 18]]
