# Propiedades de las matrices

Unas de las propiedades del producto interno entre matrices es que, son _asociativa_, _distributiva_ y _NO conmutativa_.

In [1]:
import numpy as np

In [2]:
# Definimos las matrices de ejemplo
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

## Asociativa

El agrupamiento de las matrices durante la multiplicación (producto interno) no afecta el resultado.
$$
A * (B*C) = (A*B)*C
$$

In [3]:
A_BC = A.dot(B.dot(C))
AB_C = A.dot(B).dot(C)

print(A_BC == AB_C)

[[ True  True]
 [ True  True]
 [ True  True]]


In [4]:
print(f"A_BC: \n {A_BC}")
print(f"AB_C: \n {AB_C}")

A_BC: 
 [[ 60  26]
 [145  63]
 [295 129]]
AB_C: 
 [[ 60  26]
 [145  63]
 [295 129]]


## Distributiva

La multiplicación de una matriz por la suma de dos matrices, es lo mismo que la suma de la multiplicación de la primer matriz por cada una de las matrices individualmente.

$$
A*(B+C) = (A*B) +(A*C)
$$

In [5]:
A__B_C = A.dot(B+C)
AB_AC = A.dot(B) + A.dot(C)

print(A__B_C == AB_AC)

[[ True  True]
 [ True  True]
 [ True  True]]


In [6]:
print(f"A__B_C: \n {A__B_C}")
print(f"A__B_C: \n {A__B_C}")

A__B_C: 
 [[ 26  17]
 [ 62  41]
 [122  83]]
A__B_C: 
 [[ 26  17]
 [ 62  41]
 [122  83]]


## Conmutativa

El producto interno de dos matrices NO es conmitativo, no es lo mismo multiplicar la primer matriz por la segunda que multiplicar la segunda matriz por la primera.

$$
A*B {\not =} B*A
$$

In [7]:
BC = B.dot(C)
CB = C.dot(B)

print(BC == CB)

[[False False]
 [False False]]


In [8]:
print(f"BC: \n {BC}")
print(f"CB: \n {CB}")

BC: 
 [[15  7]
 [10  4]]
CB: 
 [[ 5 10]
 [ 8 14]]


## Transposición

Otra propiedad del producto interno entre dos matrices es la transposición, dice:
- La transpueda del producto interno de dos matrices es lo mismo que el producto interno de las matrices transpuestas indiviDualmente

$$
(A*B)^t = A^t*B^t
$$

Esta propiedad nos permite:
- Operar las matrices como si fueran números, esto ayuda resolver un sistema lineal de ecuaciones sin requerir despejes complejos.
- Pasarlas de un lado a otro.
- Decidir el orden las operaciones.

In [10]:
A = np.array([[1,2,3],[7,8,9],[4,5,6]])
B = np.array([[10,11],[12,13],[14,15]])

In [11]:
AB_t = A.dot(B).T
B_tA_t = B.T.dot(A.T)

print(AB_t == B_tA_t)

[[ True  True  True]
 [ True  True  True]]


In [12]:
print(f"AB_t: \n {AB_t}")
print(f"B_tA_t: \n {B_tA_t}")

AB_t: 
 [[ 76 292 184]
 [ 82 316 199]]
B_tA_t: 
 [[ 76 292 184]
 [ 82 316 199]]
