# Tipos especiales de matrices

In [1]:
import numpy as np

## Identidad

La matriz identidad es una atriz cuadrada `nxn` donde la diagonal principal esta formada por `1` y el resto de `0`. 

Ejemplo de una matriz identidad de $3*3$:
$$
I = \begin{pmatrix}
   1 & 0 & 0\\
   0 & 1 & 0\\
   0 & 0 & 1
\end{pmatrix}
$$

Esta matriz es el elemento _neutro_ de las matrices; quiere decir que al multiplicar cualquier matriz por  la matriz identidad, la matriz original no cambia.

Suponiendo que tenemos la matriz $A$ y la matriz identidad $I$
$$
   A*I = I*A = A
$$ 

In [2]:
identidad = np.eye(4) # Función para crear una matriz identidad
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
vector = np.array([3, 5, 7, 9])
vector

array([3, 5, 7, 9])

Matriz identidad * vector:

In [4]:
identidad.dot(vector)

array([3., 5., 7., 9.])

## Inversa

Una matriz es inversa de otra cuando al multiplicarlas el resultado es la matriz identidad. <br>
La inversa de una matriz $A$ se denota como $A^{-1}$.

Suponiendo que $A$ es nuestra matriz:
$$
A * A^{-1} = I
$$

📌 No todas las matrices tienen inversa. Solo las matrices cuadradas (`nxn`) y las no singulares.

In [5]:
A = np.array([[1,0,1], [0,1,1], [-1,1,1]])
A

array([[ 1,  0,  1],
       [ 0,  1,  1],
       [-1,  1,  1]])

Inversa de la $A$:

In [6]:
inversa_A = np.linalg.inv(A)
inversa_A

array([[ 0.,  1., -1.],
       [-1.,  2., -1.],
       [ 1., -1.,  1.]])

Comprobamos la propiedad $A*A^{-1} = I$:

In [7]:
A_inversaA = A.dot(inversa_A)
A_inversaA

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Singular

Una matriz singular es una matriz cuadrada (`nxn`) que no tiene inversa. Esto ocurre cuando su determinante no es 0.

Suponiendo que $B$ es una matriz de $2*2$:
$$
B = \begin{pmatrix}
   1 & 2 \\
   2 & 4 
\end{pmatrix}
$$

$$
d = (1*4) - (1*2) = 0
$$

El determinado de la matriz $B$ es $0$, por lo tanto no tiene una inversa y es una matriz singular.

In [8]:
B = np.array([[1,2], [2,4]])
B

array([[1, 2],
       [2, 4]])

In [9]:
np.linalg.inv(B)

LinAlgError: Singular matrix

## Aplicación de la matriz inversa

La matriz inversa nos ayuda a resolver un sistema de ecuaciones lineales en su representación matricial $AX = B$, donde:
- $A$: Matriz de coeficentes.
- $X$: Matriz de variables.
- $B$: Matriz de constantes.


De las 3 matrices anteriores, conocemos la definición de $A$ y $B$, pero $X$ es una "incognita" pues no conoceos sus valores y son los que estamos buscando. 

Al final del notebook [Sistema de ecuaciones lineales](./05-Sistema-ecuaciones-lineales.ipynb), utilizando la función `linealg.solve()` de `numpy` obtuvimos los valores de las variabels, sin embargo también podemos calcularlo de forma "manual" con la matriz inversa.

Para ello solo tenemos que despejar a la matriz $X$:
$$
\begin{array}{cc}
   AX = B \\
   A^{-1}AX = A^{-1}B \\
   X = A^{-1}B
\end{array}
$$ 

Siguiendo el mismo sistema de ecuaciones lineales del [notebook anterior ](./05-Sistema-ecuaciones-lineales.ipynb):

$$
   \begin{cases}
      3x-y=5 \\
      2x -y =3
   \end{cases}
$$

Definimos la matriz de coeficientes $A$ y la de constantes $B$:

In [10]:
A = np.array([[-3,1], [-2,1]]) # Matriz de coeficientes
B = np.array([5,3]) # Matriz de constantes

Calculamos la inversa de la matriz $A$:

In [11]:
inversa_A = np.linalg.inv(A)
inversa_A

array([[-1.,  1.],
       [-2.,  3.]])

Ya tenemos la inversa $A^{-1}$, acplicamos la formula: $X = A^{-1}B$:

In [12]:
X = inversa_A.dot(B)
print(f"x = {round(X[0])}", f"y = {round(X[1])}", sep="\n")

x = -2
y = -1


Obtenemos el mismo resultado que al utilizar la función `linalg.solve()`, sin embargo el calculo "manual" resulta ser ineficiente por la forma en como los CPUs computan los numeros de estas matrices.