# Tipos especiales de matrices

In [1]:
import numpy as np

## Identidad

La matriz identidad es una atriz cuadrada `nxn` donde la diagonal principal esta formada por `1` y el resto de `0`. 

Ejemplo de una matriz identidad de $3*3$:
$$
I = \begin{pmatrix}
   1 & 0 & 0\\
   0 & 1 & 0\\
   0 & 0 & 1
\end{pmatrix}
$$

Esta matriz es el elemento _neutro_ de las matrices; quiere decir que al multiplicar cualquier matriz por  la matriz identidad, la matriz original no cambia.

Suponiendo que tenemos la matriz $A$ y la matriz identidad $I$
$$
   A*I = I*A = A
$$ 

In [3]:
identidad = np.eye(4) # Función para crear una matriz identidad
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
vector = np.array([3, 5, 7, 9])
vector

array([3, 5, 7, 9])

Matriz identidad * vector:

In [9]:
identidad.dot(vector)

array([3., 5., 7., 9.])

## Inversa

Una matriz es inversa de otra cuando al multiplicarlas el resultado es la matriz identidad. <br>
La inversa de una matriz $A$ se denota como $A^{-1}$.

Suponiendo que $A$ es nuestra matriz:
$$
A * A^{-1} = I
$$

📌 No todas las matrices tienen inversa. Solo las matrices cuadradas (`nxn`) y las no singulares.

In [11]:
A = np.array([[1,0,1], [0,1,1], [-1,1,1]])
A

array([[ 1,  0,  1],
       [ 0,  1,  1],
       [-1,  1,  1]])

Inversa de la $A$:

In [12]:
inversa_A = np.linalg.inv(A)
inversa_A

array([[ 0.,  1., -1.],
       [-1.,  2., -1.],
       [ 1., -1.,  1.]])

Comprobamos la propiedad $A*A^{-1} = I$:

In [14]:
A_inversaA = A.dot(inversa_A)
A_inversaA

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Singular

Una matriz singular es una matriz cuadrada (`nxn`) que no tiene inversa. Esto ocurre cuando su determinante no es 0.

Suponiendo que $B$ es una matriz de $2*2$:
$$
B = \begin{pmatrix}
   1 & 2 \\
   2 & 4 
\end{pmatrix}
$$

$$
d = (1*4) - (1*2) = 0
$$

El determinado de la matriz $B$ es $0$, por lo tanto no tiene una inversa y es una matriz singular.

In [15]:
B = np.array([[1,2], [2,4]])
B

array([[1, 2],
       [2, 4]])

In [16]:
np.linalg.inv(B)

LinAlgError: Singular matrix